// Generated by https://quicktype.io

export interface AUTH002Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    AccountId:   string;
    Email:       string;
    Role:        string;
    accessToken: string;
}
