// Generated by https://quicktype.io

export interface AUTH002Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    email:    string;
    password: string;
    role:     string;
}
