// Generated by https://quicktype.io

export interface AUTH005Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    token:       string;
    newPassword: string;
}
