// Generated by https://quicktype.io

export interface AUTH004Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    email: string;
}
