// Generated by https://quicktype.io

export interface BOOK004Req {
    MWHEADER: Mwheader;
    TRANRQ:   Book004Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Book004Tranrq {
    order_id: string;
}
