// Generated by https://quicktype.io

export interface CHAT002Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    pageSize:   number | null;
    pageNumber: number | null;
}
