// Generated by https://quicktype.io

export interface CHAT002Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    pageSize:   number;
    pageNumber: number;
    totalPage:  number;
    totalCount: number;
    chats:      Chat[];
}

export interface Chat {
    threadId:        string;
    orderId:         string;
    orderStatus:     string;
    displayName:     string;
    lastMessage:     null | string;
    lastMessageTime: Date | null;
}
