// Generated by https://quicktype.io

export interface CHAT003Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    threadId:   string;
    pageSize:   number;
    pageNumber: number;
}
