// Generated by https://quicktype.io

export interface CHAT003Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    room:     Room;
    messages: Message[];
}

export interface Message {
    messageId: string;
    senderId:  string;
    type:      string;
    content:   string;
    createdAt: Date;
}

export interface Room {
    threadId:        string;
    role:            string;
    buyerAccountId:  string;
    sellerAccountId: string;
    displayName:     string;
    orderId:         string;
    orderStatus:     string;
}
