// Generated by https://quicktype.io

export interface HOTEL001Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    pageSize:   number;
    pageNumber: number;
    totalPage:  number;
    totalCount: number;
    hotels:     Hotel[];
}

export interface Hotel {
    propertyId:   string;
    name:         string;
    address:      string;
    info:         string;
    avgRating:    number;
    minPrice:     number;
    images:       HotelImage[];  // 圖片物件陣列
    city:         string;
    postalCode:   string;
    availableQty: number;
}

export interface HotelImage {
    mediaId:    string;
    base64Data: string;   // Base64 編碼的圖片數據
    fileName:   string;
    mimeType:   string;   // 例如: "image/png", "image/jpeg"
    sortOrder:  number;
}
