// Generated by https://quicktype.io

export interface HOTEL001Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    petType:    string;
    checkIn:    Date;
    checkOut:   Date;
    petCount:   number;
    city:       string;
    priceMin:   number;
    priceMax:   number;
    minRating:  number;
    facilities: string[];
    page:       Page;
}

export interface Page {
    pageNumber: number;
    pageSize:   number;
}
