// Generated by https://quicktype.io

export interface HOTEL005Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    singleHotelDetail: SingleHotelDetail;
}

export interface SingleHotelDetail {
    name:            string;
    address:         string;
    info:            string;
    avgRating:       number;
    reviewCount:     number;
    roomCount:       number;
    city:            string;
    district:        string;
    propertyImages:  Image[];
    rooms:           Room[];
    reviews:         Review[];
    facilities:      Facility[];
    propertyNotice: string;
    petNotice:      string;
    checkNotice:    string;
}

export interface Facility {
    facilityId:   string;
    facilityName: string;
}

export interface Image {
    mediaId:    string;
    base64Data: string;
    fileName:   string;
    mimeType:   string;
    sortOrder:  number;
}

export interface Review {
    userId:       string;
    userName:     string;
    userAvatar:   Image[];
    priceScore:   number;
    envScore:     number;
    serviceScore: number;
    content:      string;
}

export interface Room {
    roomId:     string;
    name:       string;
    info:       string;
    roomSize:   string;
    basePrice:  number;
    totalUnits: number;
    petTypeId:  string;
    roomImages: Image[];
}
