// Generated by https://quicktype.io

export interface HOTEL005Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    propertyId: string;
    petType:    string;
    checkIn:    Date;
    checkOut:   Date;
}
