// Generated by https://quicktype.io

export interface MEDIA001Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    category:     string;
    referenceId:  string;
    successCount: number;
    failedCount:  number;
    results:      Result[];
}

export interface Result {
    mediaId:      string;
    bucket:       string;
    fileName:     string;
    sizeBytes:    number;
    mimeType:     string;
    visibility:   string;
    status:       string;
    errorMessage: null;
}
