// Generated by https://quicktype.io

export interface MEDIA004Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    propertyId?: string;
    roomId?:     string;
    accountId?:  string;
    mediaIds?:   string[];
    bucket?:     string;
}
