// Generated by https://quicktype.io

export interface MEDIA001Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    category:    string;
    referenceId: string;
    medias:      Media[];
}

export interface Media {
    base64Data: string;
    fileName:   string;
    mimeType:   string;
    bucket:     string;
    sizeBytes:  number;
    visibility: string;
    sortOrder:  number;
}
