// Generated by https://quicktype.io

export interface MEDIA004Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    totalCount: number;
    medias:     Media[];
}

export interface Media {
    mediaId:    string;
    base64Data: string;
    bucket:     string;
    fileName:   string;
    sizeBytes:  number;
    mimeType:   string;
    sortOrder?: number;
    createdAt:  Date;
    updatedAt:  Date;
}
