// Generated by https://quicktype.io

export interface MERCH004Tranrq {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    propertyId: string;
    name:       string;
    totalUnits: number;
    basePrice:  number;
    petTypeId:  string;
    info:       string;
    roomSize:   string;
    roomImages: RoomImage[];
}

export interface RoomImage {
    mediaId:   string;
    sortOrder: number;
}
