// Generated by https://quicktype.io

export interface REVIEW001Req {
    MWHEADER: Mwheader;
    TRANRQ:   Review001Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Review001Tranrq {
    orderId:      string;
    priceScore:   number;
    envScore:     number;
    serviceScore: number;
    content:      string;
}
