// Generated by https://quicktype.io

export interface REVIEW001Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    reviewId: string;
    createAt: Date;
}
