// Generated by https://quicktype.io

export interface USER007Res {
    MWHEADER: Mwheader;
    TRANRS:   USER007Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface USER007Tranrs {
    header:        Header;
    items:         Item[];
    nights:        number;
    totalQuantity: number;
    totalAmount: number;
}

export interface Header {
    orderId:          string;
    status:           string;
    checkIn:          Date;
    checkOut:         Date;
    hotelCharges:     string;
    paymentId:        string;
    paymentName:      string;
    propertyId:       string;
    propertyName:     string;
    propertyTel:      string;
    propertyAddress:  string;
    propertyImageUrl: string;
    guest:            string;
    guestName:        string;
    guestPhone:       string;
    note:             null;
}

export interface Item {
    itemId:      string;
    roomId:      string;
    roomName:    string;
    arrivalDate: Date;
    quantity:    number;
    price:       number;
    subtotal:    number;
}
