// Generated by https://quicktype.io

export interface USER002Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    name?:    string;
    phone?:   string;
    mediaId?: string;
}
