// Generated by https://quicktype.io

export interface USER007Req {
    MWHEADER: Mwheader;
    TRANRQ:   Tranrq;
}

export interface Mwheader {
    MSGID: string;
}

export interface Tranrq {
    orderId: string;
}
