// Generated by https://quicktype.io

export interface USER002Res {
    MWHEADER: Mwheader;
    TRANRS:   Tranrs;
}

export interface Mwheader {
    RETURNCODE: string;
    RETURNDESC: string;
}

export interface Tranrs {
    id:          string;
    accountId:   string;
    name:        string;
    phone:       string;
    mediaId:     string;
    mediaBase64: string;
}
